# Generated by Django 3.2.5 on 2021-07-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
