# Generated by Django 3.2.5 on 2021-07-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20210722_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contacts',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
