# Generated by Django 3.2.5 on 2021-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.JSONField(default=[])),
                ('tue', models.JSONField(default=[])),
                ('wed', models.JSONField(default=[])),
                ('thu', models.JSONField(default=[])),
                ('fri', models.JSONField(default=[])),
                ('sat', models.JSONField(default=[])),
                ('sun', models.JSONField(default=[])),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='info',
            new_name='schedule',
        ),
    ]
