# Generated by Django 3.2.5 on 2021-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='schedule',
            field=models.JSONField(default='dict'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fri',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue',
            field=models.JSONField(default='list'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed',
            field=models.JSONField(default='list'),
        ),
    ]
