# Generated by Django 3.2.5 on 2021-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='contacts',
            field=models.PositiveBigIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.CharField(default=4, max_length=65),
            preserve_default=False,
        ),
    ]
