# Generated by Django 3.2.5 on 2021-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210718_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='location',
            name='schedule',
            field=models.JSONField(default=[]),
        ),
    ]
