# Generated by Django 3.2.5 on 2021-07-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20210720_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='schedule',
            field=models.JSONField(default={}),
        ),
    ]
